import fs from "fs";
import os from "os";
import path from "path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  ENV_BACKUP_NAME,
  applyEnvUpdates,
  overlayUrl,
  parseEnv,
  postgresEnv,
  resolveStack,
  runMigration,
  stackTargetCheck,
} from "./migration-finalize";
import { FakeClient, seeded } from "./fake-db";

const PASSWORD = "0123456789abcdef0123456789abcdef0123456789abcdef";
const LEGACY_ENV = "# BlackVault configuration — generated by install.sh\nDATA_DIR=./data\nPORT=3001\n";

let repo: string;

beforeEach(() => {
  repo = fs.mkdtempSync(path.join(os.tmpdir(), "bv-finalize-"));
  fs.mkdirSync(path.join(repo, "data", "db"), { recursive: true });
  fs.writeFileSync(path.join(repo, "data", "db", "vault.db"), "not really sqlite");
  fs.writeFileSync(path.join(repo, ".env"), `${LEGACY_ENV}BLACKVAULT_POSTGRES_PASSWORD=${PASSWORD}\n`, { mode: 0o644 });
});

afterEach(() => {
  fs.rmSync(repo, { recursive: true, force: true });
});

const marker = () => path.join(repo, "data", "db", ".migrated");
const envText = () => fs.readFileSync(path.join(repo, ".env"), "utf8");
const backup = () => path.join(repo, ENV_BACKUP_NAME);

async function run(
  extra: { dryRun?: boolean; force?: boolean; writeEnv?: boolean; url?: string; sqlitePath?: string; target?: FakeClient } = {},
) {
  const stack = resolveStack(repo);
  const lines: string[] = [];
  const code = await runMigration({
    stack,
    sqlitePath: extra.sqlitePath ?? stack.stackSqlitePath,
    postgresUrl: extra.url ?? overlayUrl(PASSWORD),
    dryRun: extra.dryRun ?? false,
    force: extra.force ?? false,
    writeEnv: extra.writeEnv ?? false,
    source: seeded().asDb(),
    connectTarget: () => (extra.target ?? new FakeClient()).asDb(),
    log: (l) => lines.push(l),
    now: () => new Date("2026-09-22T12:00:00.000Z"),
  });
  return { code, out: lines.join("\n") };
}

describe("runMigration", () => {
  it("on a verified copy writes .migrated and switches .env, keeping every other line", async () => {
    const before = envText();
    const { code, out } = await run();
    expect(code).toBe(0);

    const record = JSON.parse(fs.readFileSync(marker(), "utf8"));
    expect(record.migratedAt).toBe("2026-09-22T12:00:00.000Z");
    expect(record.source).toBe(path.join(repo, "data", "db", "vault.db"));
    expect(record.totalRows).toBe(32);
    expect(record.counts.Firearm).toBe(2);
    expect(Object.keys(record.counts)).toHaveLength(16);
    expect(record.target).not.toContain(PASSWORD);

    const env = parseEnv(envText());
    expect(env.get("COMPOSE_PROFILES")).toBe("postgres");
    expect(env.get("BLACKVAULT_DB_PROVIDER")).toBe("postgres");
    expect(env.get("BLACKVAULT_POSTGRES_PASSWORD")).toBe(PASSWORD);
    expect(env.get("BLACKVAULT_DATABASE_URL")).toBe(`postgresql://blackvault:${PASSWORD}@db:5432/blackvault`);
    // The generic names are never written: a shell variable would override them.
    expect(env.has("DB_PROVIDER")).toBe(false);
    expect(env.has("DATABASE_URL")).toBe(false);
    expect(env.has("POSTGRES_PASSWORD")).toBe(false);
    expect(envText()).toContain("# BlackVault configuration — generated by install.sh\nDATA_DIR=./data\nPORT=3001\n");

    expect(fs.readFileSync(backup(), "utf8")).toBe(before);
    expect(fs.statSync(path.join(repo, ".env")).mode & 0o777).toBe(0o600);
    expect(fs.statSync(backup()).mode & 0o777).toBe(0o600);
    expect(out).not.toContain(PASSWORD);
    expect(out).toContain("BLACKVAULT_DB_PROVIDER: (not set) -> postgres");
    expect(out).toContain("BLACKVAULT_DATABASE_URL: (not set) -> postgresql://blackvault:****@db:5432/blackvault");
    expect(fs.readdirSync(repo).filter((f) => f.includes(".tmp-"))).toEqual([]);
  });

  it("writes nothing on a dry run", async () => {
    const before = envText();
    const { code, out } = await run({ dryRun: true });
    expect(code).toBe(0);
    expect(out).toContain("nothing written");
    expect(fs.existsSync(marker())).toBe(false);
    expect(fs.existsSync(backup())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("writes nothing when verification fails and the copy is rolled back", async () => {
    const before = envText();
    const target = new FakeClient();
    target.delegates.batteryChangeLog.countShortBy = 1;
    const { code, out } = await run({ target });
    expect(code).toBe(1);
    expect(out).toContain("rolled back");
    expect(fs.existsSync(marker())).toBe(false);
    expect(fs.existsSync(backup())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("writes nothing when the non-empty target is refused", async () => {
    const before = envText();
    const target = new FakeClient();
    target.delegates.firearm.rows = [{ id: "existing" }];
    const { code, out } = await run({ target });
    expect(code).toBe(1);
    expect(out).toContain("REFUSING");
    expect(fs.existsSync(marker())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("refuses to run when .migrated already exists, and writes nothing", async () => {
    fs.writeFileSync(marker(), JSON.stringify({ migratedAt: "2026-01-01T00:00:00.000Z" }));
    const before = envText();
    let connected = false;
    const stack = resolveStack(repo);
    const lines: string[] = [];
    const code = await runMigration({
      stack,
      sqlitePath: stack.stackSqlitePath,
      postgresUrl: overlayUrl(PASSWORD),
      dryRun: false,
      force: false,
      writeEnv: false,
      source: seeded().asDb(),
      connectTarget: () => {
        connected = true;
        return new FakeClient().asDb();
      },
      log: (l) => lines.push(l),
    });
    expect(code).toBe(1);
    expect(lines.join("\n")).toContain("already been migrated to PostgreSQL on 2026-01-01T00:00:00.000Z");
    expect(connected).toBe(false);
    expect(envText()).toBe(before);
    expect(JSON.parse(fs.readFileSync(marker(), "utf8"))).toEqual({ migratedAt: "2026-01-01T00:00:00.000Z" });
  });

  it("refuses an existing .migrated on a dry run too", async () => {
    fs.writeFileSync(marker(), "{}");
    expect((await run({ dryRun: true })).code).toBe(1);
  });

  it("runs again over an existing .migrated with --force, keeping the first .env backup", async () => {
    expect((await run()).code).toBe(0);
    const firstBackup = fs.readFileSync(backup(), "utf8");
    const { code } = await run({ force: true });
    expect(code).toBe(0);
    expect(fs.readFileSync(backup(), "utf8")).toBe(firstBackup);
    expect(fs.readdirSync(repo).filter((f) => f.startsWith(`${ENV_BACKUP_NAME}.`))).toHaveLength(1);
  });

  it("does not switch .env for a target that is not the stack's database, but prints the lines", async () => {
    const before = envText();
    const { code, out } = await run({ url: `postgresql://blackvault:${PASSWORD}@192.168.1.5:5432/blackvault` });
    expect(code).toBe(0);
    expect(out).toContain("VERIFIED");
    expect(out).toContain("will NOT be switched");
    expect(out).toContain(
      "BLACKVAULT_DATABASE_URL=postgresql://blackvault:${BLACKVAULT_POSTGRES_PASSWORD}@db:5432/blackvault",
    );
    expect(out).not.toContain(PASSWORD);
    expect(fs.existsSync(marker())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("--write-env accepts another host/port when everything else matches", async () => {
    const { code } = await run({ url: `postgresql://blackvault:${PASSWORD}@10.0.0.2:5432/blackvault`, writeEnv: true });
    expect(code).toBe(0);
    expect(fs.existsSync(marker())).toBe(true);
    expect(parseEnv(envText()).get("BLACKVAULT_DB_PROVIDER")).toBe("postgres");
  });

  it("does not switch .env when the source is not this install's vault.db, even with --write-env", async () => {
    const other = path.join(repo, "elsewhere.db");
    fs.writeFileSync(other, "x");
    const before = envText();
    const { code, out } = await run({ sqlitePath: other, writeEnv: true });
    expect(code).toBe(0);
    expect(out).toContain("the source is not this install's database");
    expect(fs.existsSync(marker())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("does not switch .env when .env has no BLACKVAULT_POSTGRES_PASSWORD", async () => {
    fs.writeFileSync(path.join(repo, ".env"), LEGACY_ENV);
    const { code, out } = await run();
    expect(code).toBe(0);
    expect(out).toContain(".env has no BLACKVAULT_POSTGRES_PASSWORD");
    expect(fs.existsSync(marker())).toBe(false);
    expect(envText()).toBe(LEGACY_ENV);
  });

  it("leaves .env alone when .migrated cannot be written (e.g. data/db owned by the container)", async () => {
    const before = envText();
    const dbDir = path.join(repo, "data", "db");
    fs.chmodSync(dbDir, 0o500);
    try {
      const { code, out } = await run();
      expect(code).toBe(1);
      expect(out).toContain("could not be written");
      expect(out).toContain(".env was NOT switched");
    } finally {
      fs.chmodSync(dbDir, 0o700);
    }
    expect(fs.existsSync(marker())).toBe(false);
    expect(fs.existsSync(backup())).toBe(false);
    expect(envText()).toBe(before);
  });

  it("puts .migrated in DATA_DIR/db when DATA_DIR is elsewhere", async () => {
    const dataDir = path.join(repo, "my data");
    fs.mkdirSync(path.join(dataDir, "db"), { recursive: true });
    fs.writeFileSync(path.join(dataDir, "db", "vault.db"), "x");
    fs.writeFileSync(path.join(repo, ".env"), `DATA_DIR="${dataDir}"\nBLACKVAULT_POSTGRES_PASSWORD=${PASSWORD}\n`);
    expect((await run()).code).toBe(0);
    expect(fs.existsSync(path.join(dataDir, "db", ".migrated"))).toBe(true);
    expect(fs.existsSync(marker())).toBe(false);
  });
});

describe("stackTargetCheck", () => {
  it("rejects a wrong password or database", () => {
    const stack = resolveStack(repo);
    const wrongPw = stackTargetCheck({
      targetUrl: overlayUrl("deadbeef"),
      sqlitePath: stack.stackSqlitePath,
      stack,
      writeEnv: false,
    });
    expect(wrongPw.ok).toBe(false);
    const wrongDb = stackTargetCheck({
      targetUrl: `postgresql://blackvault:${PASSWORD}@127.0.0.1:55432/other`,
      sqlitePath: stack.stackSqlitePath,
      stack,
      writeEnv: true,
    });
    expect(wrongDb.ok).toBe(false);
  });
});

describe("applyEnvUpdates", () => {
  it("replaces in place, drops duplicates, appends missing keys and merges profiles", () => {
    const { text } = applyEnvUpdates(
      "# c\nBLACKVAULT_DB_PROVIDER=sqlite\nCOMPOSE_PROFILES=extra\nPORT=3000\nBLACKVAULT_DB_PROVIDER=\"sqlite\"\n" +
        "# BLACKVAULT_DATABASE_URL=commented\nDB_PROVIDER=sqlite\n",
      postgresEnv(PASSWORD),
    );
    expect(text).toBe(
      "# c\nBLACKVAULT_DB_PROVIDER=postgres\nCOMPOSE_PROFILES=extra,postgres\nPORT=3000\n" +
        "# BLACKVAULT_DATABASE_URL=commented\nDB_PROVIDER=sqlite\n" +
        "# PostgreSQL - written by npm run migrate:to-postgres\n" +
        `BLACKVAULT_POSTGRES_PASSWORD=${PASSWORD}\n` +
        `BLACKVAULT_DATABASE_URL=postgresql://blackvault:${PASSWORD}@db:5432/blackvault\n`,
    );
  });

  it("keeps CRLF line endings", () => {
    const { text } = applyEnvUpdates("DATA_DIR=C:\\bv\r\nPORT=3000\r\n", postgresEnv(PASSWORD));
    expect(text.split("\r\n")).toHaveLength(8); // 2 kept + comment + 4 keys + trailing ""
    expect(text.replace(/\r\n/g, "")).not.toContain("\n");
  });
});
