#!/usr/bin/env bash
#
# dev.sh — run BlackVault locally, without Docker.
#
# Handles the setup that `npm run dev` does not: installing dependencies,
# writing a local .env, generating the Prisma client, and applying migrations.
# Safe to re-run; every step is a no-op when it is already done.
#
#   ./dev.sh                start the dev server on :3000
#   ./dev.sh --port 4000    start on a different port
#   ./dev.sh --fresh        recreate the local database from migrations, then seed
#   ./dev.sh --seed         seed the existing database, then start
#   ./dev.sh --studio       open Prisma Studio instead of the dev server
#   ./dev.sh --setup-only   do the setup steps and exit without starting anything
#   ./dev.sh --help
#
# This touches ONLY the local SQLite file at prisma/prisma/dev.db. It never
# reads or writes ./data, which is where Docker keeps real installs.

set -euo pipefail

cd "$(dirname "$0")"
ROOT="$PWD"

# ── Pretty output ─────────────────────────────────────────────
if [ -t 1 ]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
  YELLOW=$'\033[33m'; CYAN=$'\033[36m'; RESET=$'\033[0m'
else
  BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; CYAN=""; RESET=""
fi

step() { printf "%s==>%s %s\n" "$CYAN" "$RESET" "$1"; }
ok()   { printf "%s  ok%s %s\n" "$GREEN" "$RESET" "$1"; }
warn() { printf "%s  !!%s %s\n" "$YELLOW" "$RESET" "$1"; }
die()  { printf "%s ERROR%s %s\n" "$RED" "$RESET" "$1" >&2; exit 1; }

# Print the header comment block (everything from line 3 until the first non-comment line).
usage() {
  awk 'NR<3 {next} /^#/ {sub(/^# ?/, ""); print; next} {exit}' "$0"
  exit 0
}

# ── Arguments ─────────────────────────────────────────────────
PORT="3000"
FRESH=0
SEED=0
STUDIO=0
SETUP_ONLY=0

while [ $# -gt 0 ]; do
  case "$1" in
    --port)       PORT="${2:-}"; [ -n "$PORT" ] || die "--port needs a value"; shift 2 ;;
    --port=*)     PORT="${1#*=}"; shift ;;
    --fresh)      FRESH=1; SEED=1; shift ;;
    --seed)       SEED=1; shift ;;
    --studio)     STUDIO=1; shift ;;
    --setup-only) SETUP_ONLY=1; shift ;;
    -h|--help)    usage ;;
    *)            die "unknown option: $1  (try --help)" ;;
  esac
done

# ── Prerequisites ─────────────────────────────────────────────
step "Checking prerequisites"

command -v node >/dev/null 2>&1 || die "node is not installed. Install Node 20.12 or newer."
command -v npm  >/dev/null 2>&1 || die "npm is not installed."

# 20.12 is the floor: scripts/load-env.ts uses process.loadEnvFile (added in 20.12).
NODE_VERSION="$(node --version | sed 's/^v//')"
NODE_MAJOR="$(echo "$NODE_VERSION" | cut -d. -f1)"
NODE_MINOR="$(echo "$NODE_VERSION" | cut -d. -f2)"
if [ "$NODE_MAJOR" -lt 20 ] || { [ "$NODE_MAJOR" -eq 20 ] && [ "$NODE_MINOR" -lt 12 ]; }; then
  die "Node $NODE_VERSION is too old. BlackVault needs Node 20.12 or newer."
fi
if [ "$NODE_MAJOR" -ne 20 ]; then
  warn "Running Node $NODE_MAJOR; the Docker image uses Node 20. Usually fine, but if you hit"
  warn "something that only breaks locally, try Node 20 before assuming it is a real bug."
fi
ok "node $(node --version), npm $(npm --version)"

# ── Database provider ─────────────────────────────────────────
# Local development uses SQLite. Postgres runs via docker compose, not this script.
DB_PROVIDER="${DB_PROVIDER:-sqlite}"

# Forward-compatible with the per-provider schema layout; falls back to the
# single schema that exists today.
if [ -f "prisma/${DB_PROVIDER}/schema.prisma" ]; then
  SCHEMA="prisma/${DB_PROVIDER}/schema.prisma"
elif [ -f "prisma/schema.prisma" ]; then
  SCHEMA="prisma/schema.prisma"
else
  die "No Prisma schema found. Expected prisma/schema.prisma or prisma/${DB_PROVIDER}/schema.prisma"
fi

if [ "$DB_PROVIDER" = "sqlite" ]; then
  DB_FILE="$ROOT/prisma/prisma/dev.db"
  DEFAULT_URL="file:$DB_FILE"
else
  DB_FILE=""
  DEFAULT_URL="${DATABASE_URL:-}"
  [ -n "$DEFAULT_URL" ] || die "DB_PROVIDER=$DB_PROVIDER needs DATABASE_URL to be set."
fi

# ── .env ──────────────────────────────────────────────────────
step "Checking .env"

if [ ! -f .env ]; then
  cat > .env <<ENVEOF
# Generated by ./dev.sh for local development.
# Docker installs use their own .env — this one is gitignored.
DB_PROVIDER=$DB_PROVIDER
DATABASE_URL=$DEFAULT_URL
DATA_DIR=./data
PORT=$PORT
ENVEOF
  ok "wrote .env (local SQLite at prisma/prisma/dev.db)"
else
  if ! grep -q '^DATABASE_URL=' .env; then
    echo "DATABASE_URL=$DEFAULT_URL" >> .env
    ok "added a missing DATABASE_URL to your existing .env"
  else
    ok ".env already present — leaving it alone"
  fi
fi

# The dev server and Prisma CLI both read this.
export DATABASE_URL="${DATABASE_URL:-$DEFAULT_URL}"
export DB_PROVIDER

# ── Dependencies ──────────────────────────────────────────────
step "Checking dependencies"

if [ ! -d node_modules ]; then
  ok "node_modules missing — running npm install (this takes a minute)"
  npm install
elif [ package-lock.json -nt node_modules ]; then
  ok "package-lock.json is newer than node_modules — reinstalling"
  npm install
else
  ok "dependencies up to date"
fi

# ── Database ──────────────────────────────────────────────────
if [ "$FRESH" -eq 1 ]; then
  step "Recreating the local database"
  if [ -n "$DB_FILE" ] && [ -f "$DB_FILE" ]; then
    # Suffix stays *.db so .gitignore keeps the backup out of git.
    BACKUP="${DB_FILE%.db}.backup-$(date +%Y%m%d-%H%M%S).db"
    mv "$DB_FILE" "$BACKUP"
    ok "previous database moved to $(basename "$BACKUP")"
  fi
  rm -f "${DB_FILE}-journal" 2>/dev/null || true
else
  step "Preparing the database"
fi

if [ -n "$DB_FILE" ]; then
  mkdir -p "$(dirname "$DB_FILE")"
fi

npm run db:generate >/dev/null
ok "Prisma client generated"

# Always `migrate deploy` — the same path production and CI use. Never
# `db push`: it syncs the schema without recording migrations, so the next
# schema change sees drift and `prisma migrate dev` demands a database reset.
#
# A database whose migration ledger disagrees with its schema (for example one
# built with `db push` by an older version of this script) fails here with
# P3018. Rebuilding it from the full history fixes that.
if ! npx prisma migrate deploy --schema "$SCHEMA"; then
  die "migrations failed to apply. If this database predates the current migration history, rebuild it with: ./dev.sh --fresh"
fi
ok "migrations applied"

if [ "$SEED" -eq 1 ]; then
  step "Seeding"
  npx prisma db seed || warn "seed failed — continuing with an empty database"
fi

# ── Go ────────────────────────────────────────────────────────
if [ "$SETUP_ONLY" -eq 1 ]; then
  step "Setup complete"
  echo ""
  echo "  Start the app with: ${BOLD}./dev.sh${RESET}"
  exit 0
fi

if [ "$STUDIO" -eq 1 ]; then
  step "Opening Prisma Studio"
  echo "  ${DIM}Browse and edit the local database. Ctrl-C to quit.${RESET}"
  echo ""
  exec npx prisma studio --schema "$SCHEMA"
fi

step "Starting the dev server"
echo ""
echo "  ${BOLD}http://localhost:$PORT${RESET}"
echo "  ${DIM}Also reachable from your phone on this network — see Settings for the QR code.${RESET}"
echo "  ${DIM}Database: $([ -n "$DB_FILE" ] && echo "${DB_FILE#"$ROOT"/}" || echo "$DB_PROVIDER")${RESET}"
echo "  ${DIM}Ctrl-C to stop.${RESET}"
echo ""

exec npx next dev -H 0.0.0.0 -p "$PORT"
